version: "3.7"
volumes:
  grafana:
  prometheus:
  letsencrypt:

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana:/var/lib/grafana

  nginx:
    image: sebohe/nginx:latest
    deploy:
      mode: global
    environment:
      DOMAIN_URL: "hashcloak.com"
      SUBDOMAINS: "prometheus:9090 grafana:3000"
      EMAIL: "sebasheston@pm.me"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - letsencrypt:/etc/letsencrypt
